# Count Rows
SELECT
  COUNT(*) AS row_count
FROM `monarch-money-481323.marketing_data.fct_users`;
# 100,000

# Timespan 
SELECT 
  MIN(REGISTERED_AT) AS min_registered,
  MAX(REGISTERED_AT) AS max_registed,
  MIN(FREE_TRIAL_STARTED_AT) AS min_trial,
  MAX(FREE_TRIAL_STARTED_AT) AS max_trial,
  MIN(SUBSCRIPTION_STARTED_AT) AS min_subs
FROM `monarch-money-481323.marketing_data.fct_users` ;
# 12/01/2024 - 3/03/2025

# Count Null Rows
SELECT 
  SUM(CASE WHEN USER_ID_INT IS NULL THEN 1 ELSE 0 END) AS null_user_rows,
  COUNT(*) AS total_rows
FROM `monarch-money-481323.marketing_data.fct_users` ;
# No null values

# Distinct users vs total users
SELECT 
  COUNT(USER_ID_INT) AS total_rows,
  COUNT(DISTINCT USER_ID_INT) AS distinct_users
FROM `monarch-money-481323.marketing_data.fct_users` ;
# All users are unique

# Nulls by Columns
SELECT 
  COUNT(*) AS total,
  SUM(CASE WHEN REGISTERED_AT IS NULL THEN 1 ELSE 0 END) AS null_registered_at,
  SUM(CASE WHEN SIGNUP_CLIENT_PLATFORM IS NULL THEN 1 ELSE 0 END) AS null_SIGNUP_CLIENT_PLATFORM,
  SUM(CASE WHEN EXTERNAL_AUTH_PROVIDER IS NULL THEN 1 ELSE 0 END) AS null_EXTERNAL_AUTH_PROVIDER,
  SUM(CASE WHEN IS_VERIFIED IS NULL THEN 1 ELSE 0 END) AS null_IS_VERIFIED,
  SUM(CASE WHEN INTERNAL_ATTRIBUTION_CHANNEL IS NULL THEN 1 ELSE 0 END) AS null_INTERNAL_ATTRIBUTION_CHANNEL,
  SUM(CASE WHEN USER_SELECTED_ATTRIBUTION IS NULL THEN 1 ELSE 0 END) AS null_USER_SELECTED_ATTRIBUTION,
  SUM(CASE WHEN FREE_TRIAL_STARTED_AT IS NULL THEN 1 ELSE 0 END) AS null_FREE_TRIAL_STARTED_AT,
  SUM(CASE WHEN TRIAL_ENDS_AT IS NULL THEN 1 ELSE 0 END) AS null_TRIAL_ENDS_AT,
  SUM(CASE WHEN SUBSCRIPTION_STARTED_AT IS NULL THEN 1 ELSE 0 END) AS null_SUBSCRIPTION_STARTED_AT,
  SUM(CASE WHEN PLAN_PERIOD IS NULL THEN 1 ELSE 0 END) AS null_PLAN_PERIOD,
  SUM(CASE WHEN PLAN_PRICE_PAID IS NULL THEN 1 ELSE 0 END) AS null_PLAN_PRICE_PAID,
  SUM(CASE WHEN PLAN_BASE_PRICE IS NULL THEN 1 ELSE 0 END) AS null_PLAN_BASE_PRICE,
  SUM(CASE WHEN LIFETIME_VALUE IS NULL THEN 1 ELSE 0 END) AS null_LIFETIME_VALUE,
  SUM(CASE WHEN STARTED_TRIAL IS NULL THEN 1 ELSE 0 END) AS null_STARTED_TRIAL,
  SUM(CASE WHEN SUBSCRIBED IS NULL THEN 1 ELSE 0 END) AS null_SUBSCRIBED
FROM `monarch-money-481323.marketing_data.fct_users` ;
# Nulls are inline with those who did not start a trial or subscription



