CREATE TABLE `monarch-money-481323.marketing_data.fct_funnel_summary` AS(
  WITH BASE AS (
  SELECT
    USER_ID_INT,
    IS_VERIFIED,
    STARTED_TRIAL,
    SUBSCRIBED,
    INTERNAL_ATTRIBUTION_CHANNEL,
    SIGNUP_CLIENT_PLATFORM,
    EXTERNAL_AUTH_PROVIDER
  FROM `monarch-money-481323.marketing_data.fact_users` 
),
SUMMARIES AS (
  SELECT
    'OVERALL' AS BEAKDOWN_TYPE,
    'OVERALL' AS BREAKDOWN_VALUE,
    COUNT(DISTINCT USER_ID_INT) AS SIGNUPS,
    COUNT(DISTINCT IF(IS_VERIFIED, USER_ID_INT, NULL)) AS VERIFIED_USERS,
    COUNT(DISTINCT IF(STARTED_TRIAL = 1, USER_ID_INT, NULL)) AS TRIAL_STARTS,
    COUNT(DISTINCT IF(SUBSCRIBED = 1, USER_ID_INT, NULL)) AS PAID_SUBSCRIBERS
    FROM BASE

UNION ALL

SELECT
  'CHANNEL' AS BEAKDOWN_TYPE,
  COALESCE(INTERNAL_ATTRIBUTION_CHANNEL, 'UNKOWN') AS BREAKDOWN_VALUE,
  COUNT(DISTINCT USER_ID_INT) AS SIGNUPS,
  COUNT(DISTINCT IF(IS_VERIFIED, USER_ID_INT, NULL)) AS VERIFIED_USERS,
  COUNT(DISTINCT IF(STARTED_TRIAL = 1, USER_ID_INT, NULL)) AS TRIAL_STARTS,
  COUNT(DISTINCT IF(SUBSCRIBED = 1, USER_ID_INT, NULL)) AS PAID_SUBSCRIBERS
FROM BASE
GROUP BY 1,2

UNION ALL

SELECT 
  'SIGNUP_PLATFORM' AS BEAKDOWN_TYPE,
  COALESCE(SIGNUP_CLIENT_PLATFORM, 'UNKOWN') AS BREAKDOWN_VALUE,
  COUNT(DISTINCT USER_ID_INT) AS SIGNUPS,
  COUNT(DISTINCT IF(IS_VERIFIED, USER_ID_INT, NULL)) AS VERIFIED_USERS,
  COUNT(DISTINCT IF(STARTED_TRIAL = 1, USER_ID_INT, NULL)) AS TRIAL_STARTED,
    COUNT(DISTINCT IF(SUBSCRIBED = 1, USER_ID_INT, NULL)) AS PAID_SUBSCRIBERS
FROM BASE
GROUP BY 1,2

UNION ALL

SELECT
  'AUTH_PROVIDER' AS BREAKDOWN_TYPE,
  COALESCE(EXTERNAL_AUTH_PROVIDER, 'UNKOWN') AS BREAKDOWN_VALUE,
    COUNT(DISTINCT USER_ID_INT) AS SIGNUPS,
  COUNT(DISTINCT IF(IS_VERIFIED, USER_ID_INT, NULL)) AS VERIFIED_USERS,
  COUNT(DISTINCT IF(STARTED_TRIAL = 1, USER_ID_INT, NULL)) AS TRIAL_STARTED,
    COUNT(DISTINCT IF(SUBSCRIBED = 1, USER_ID_INT, NULL)) AS PAID_SUBSCRIBERS
FROM BASE
GROUP BY 1,2
)

SELECT
  BEAKDOWN_TYPE,
  BREAKDOWN_VALUE,
  SIGNUPS,
  VERIFIED_USERS,
  TRIAL_STARTS,
  PAID_SUBSCRIBERS,

  SAFE_DIVIDE(VERIFIED_USERS, SIGNUPS) AS SIGNUP_TO_VERIFIED_RATE,
  SAFE_DIVIDE(TRIAL_STARTS, SIGNUPS) AS SIGNUP_TO_TRIAL_RATE,
  SAFE_DIVIDE(PAID_SUBSCRIBERS, SIGNUPS) AS SIGNUP_TO_PAID_RATE,
  SAFE_DIVIDE(PAID_SUBSCRIBERS, TRIAL_STARTS) AS TRIAL_TO_PAID_RATE
FROM SUMMARIES
);