CREATE TABLE `monarch-money-481323.marketing_data.fct_channel_signup_cohort_day` AS (
  WITH daily_users AS (
  SELECT 
    DATE(U.REGISTERED_AT) AS DATE,
    A.INTERNAL_ATTRIBUTION_CHANNEL AS CHANNEL,
    COUNT(DISTINCT U.USER_ID_INT) AS SIGNUPS,
    COUNT(DISTINCT CASE WHEN T.USER_ID_INT IS NOT NULL THEN U.USER_ID_INT END) AS TRIAL_STARTS,
    COUNT(DISTINCT CASE WHEN S.USER_ID_INT IS NOT NULL THEN U.USER_ID_INT END) AS PAID_SUBSCRIBERS,
    SUM(CASE WHEN S.USER_ID_INT IS NOT NULL THEN S.LIFETIME_VALUE ELSE 0 END) AS TOTAL_LTV,
    SUM(CASE WHEN S.USER_ID_INT IS NOT NULL THEN S.PLAN_PRICE_PAID ELSE 0 END) AS TOTAL_PRICE_PAID 
  FROM `monarch-money-481323.marketing_data.users` U
  LEFT JOIN `monarch-money-481323.marketing_data.attribution` A ON U.USER_ID_INT = A.USER_ID_INT 
  LEFT JOIN `monarch-money-481323.marketing_data.trial` T ON U.USER_ID_INT = T.USER_ID_INT
  LEFT JOIN `monarch-money-481323.marketing_data.subscription` S ON U.USER_ID_INT = S.USER_ID_INT
  GROUP BY 1,2
),

daily_spend AS (
  SELECT 
    DATE,
    AD_CHANNEL AS CHANNEL,
    SUM(AD_SPEND) AS SPEND
  FROM `monarch-money-481323.marketing_data.ad_spend` 
  GROUP BY 1,2
)

SELECT 
  D.DATE,
  D.CHANNEL,
  D.SIGNUPS,
  D.TRIAL_STARTS,
  D.PAID_SUBSCRIBERS,
  D.TOTAL_LTV,
  D.TOTAL_PRICE_PAID,
  S.SPEND,
  SAFE_DIVIDE(S.SPEND, NULLIF(D.SIGNUPS,0)) AS CAC_PER_SIGNUP,
  SAFE_DIVIDE(S.SPEND, NULLIF(D.TRIAL_STARTS,0)) AS CAC_PER_TRIAL_START,
  SAFE_DIVIDE(S.SPEND, NULLIF(D.PAID_SUBSCRIBERS,0)) AS CAC_PER_PAID_SUBSCRIBER,
  SAFE_DIVIDE(D.TOTAL_LTV, NULLIF(S.SPEND,0)) AS ROAS_LTV,
  SAFE_DIVIDE(
    SAFE_DIVIDE(D.TOTAL_LTV, NULLIF(D.PAID_SUBSCRIBERS,0)),
    SAFE_DIVIDE(S.SPEND, NULLIF(D.PAID_SUBSCRIBERS,0))
  ) AS LTV_TO_CAC_RATIO
FROM daily_users D
LEFT JOIN daily_spend S ON D.DATE = S.DATE AND D.CHANNEL = S.CHANNEL
)