CREATE TABLE `monarch-money-481323.marketing_data.fct_pricing` AS
(
  SELECT 
  USER_ID_INT,
  REGISTERED_AT,
  INTERNAL_ATTRIBUTION_CHANNEL,
  USER_SELECTED_ATTRIBUTION,
  SIGNUP_CLIENT_PLATFORM,
  EXTERNAL_AUTH_PROVIDER,

  SUBSCRIPTION_STARTED_AT,
  PLAN_PERIOD,
  PLAN_BASE_PRICE,
  PLAN_PRICE_PAID,
  LIFETIME_VALUE,

  (PLAN_BASE_PRICE - PLAN_PRICE_PAID) AS DISCOUNT_AMT,
  SAFE_DIVIDE((PLAN_BASE_PRICE - PLAN_PRICE_PAID), PLAN_BASE_PRICE) AS DISCOUNT_PERCENT,

  CASE
    WHEN PLAN_PRICE_PAID IS NULL OR PLAN_BASE_PRICE IS NULL THEN 'UNKNOWN'
    WHEN PLAN_PRICE_PAID = PLAN_BASE_PRICE THEN 'NO-DISCOUNT'
    WHEN SAFE_DIVIDE((PLAN_BASE_PRICE - PLAN_PRICE_PAID), PLAN_BASE_PRICE) BETWEEN 0.29 AND 0.31 THEN '30%'
    WHEN SAFE_DIVIDE((PLAN_BASE_PRICE - PLAN_PRICE_PAID), PLAN_BASE_PRICE) BETWEEN 0.49 AND .51 THEN '50%'
    ELSE 'OTHER-DISCOUNT'
  END AS DISCOUNT_BUCKET

 FROM `monarch-money-481323.marketing_data.fct_users`
WHERE SUBSCRIBED = 1
);