CREATE TABLE `monarch-money-481323.marketing_data.fct_users` AS (
  SELECT 
  U.USER_ID_INT,
  U.REGISTERED_AT,
  U.SIGNUP_CLIENT_PLATFORM,
  U.EXTERNAL_AUTH_PROVIDER,
  U.IS_VERIFIED,

  A.INTERNAL_ATTRIBUTION_CHANNEL,
  A.USER_SELECTED_ATTRIBUTION,

  T.FREE_TRIAL_STARTED_AT,
  T.TRIAL_ENDS_AT,

  S.SUBSCRIPTION_STARTED_AT,
  S.PLAN_PERIOD,
  S.PLAN_PRICE_PAID,
  S.PLAN_BASE_PRICE,
  S.LIFETIME_VALUE,

  CASE WHEN T.USER_ID_INT IS NOT NULL THEN 1 ELSE 0 END AS STARTED_TRIAL,
  CASE WHEN S.USER_ID_INT IS NOT NULL THEN 1 ELSE 0 END AS SUBSCRIBED

  FROM `monarch-money-481323.marketing_data.users` U 
  LEFT JOIN  `monarch-money-481323.marketing_data.attribution` A ON U.USER_ID_INT = A.USER_ID_INT
  LEFT JOIN `monarch-money-481323.marketing_data.trial` T ON U.USER_ID_INT = T.USER_ID_INT
  LEFT JOIN `monarch-money-481323.marketing_data.subscription` S ON U.USER_ID_INT = S.USER_ID_INT
  )
